using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UFPCore.Prediction_constants
{
    public class Matches
    {
        public const string Match1H = "Liverpool";
        public const string Match1A = "Manchester United";
        public const string Match2H = "Tottenham";
        public const string Match2A = "Arsenal";
        public const string Match3H = "Manchester City";
        public const string Match3A = "Liverpool";
        public const string Match4H = "Chelsea";
        public const string Match4A = "Wolves";
        public const string Match5H = "Watford";
        public const string Match5A = "Leicester";
        public const string Match6H = "Arsenal";
        public const string Match6A = "Everton";
        public const string Match7H = "Brighton";
        public const string Match7A = "Newcastle";
        public const string Match8H = "Aston Villa";
        public const string Match8A = "Liverpool";
        public const string Match9H = "Bournemouth";
        public const string Match9A = "Brighton";
        public const string Match10H = "Manchester United";
        public const string Match10A = "Chelsea";
        public const string Match11H = "Norwich";
        public const string Match11A = "Sheffield Utd";
        public const string Match12H = "Chelsea";
        public const string Match12A = "Brighton";
        public const string Match13H = "Manchester City";
        public const string Match13A = "Leicester";
        public const string Match14H = "Aston Villa";
        public const string Match14A = "Newcastle";
        public const string Match15H = "Everton";
        public const string Match15A = "Crystal Palace";
        public const string Match16H = "Southampton";
        public const string Match16A = "Wolves";
        public const string Match17H = "Tottenham";
        public const string Match17A = "Wolves";
        public const string Match18H = "Brighton";
        public const string Match18A = "Liverpool";
        public const string Match19H = "Arsenal";
        public const string Match19A = "Manchester United";
        public const string Match20H = "Brighton";
        public const string Match20A = "Watford";
        public const string Match21H = "Wolves";
        public const string Match21A = "Aston Villa";
        public const string Match22H = "Watford";
        public const string Match22A = "Chelsea";
        public const string Match23H = "Arsenal";
        public const string Match23A = "Bournemouth";
        public const string Match24H = "Liverpool";
        public const string Match24A = "Manchester United";
        public const string Match25H = "Aston Villa";
        public const string Match25A = "Southampton";
        public const string Match26H = "Watford";
        public const string Match26A = "Manchester City";
        public const string Match27H = "Leicester";
        public const string Match27A = "Tottenham";
        public const string Match28H = "Crystal Palace";
        public const string Match28A = "Everton";
        public const string Match29H = "Newcastle";
        public const string Match29A = "Leicester";
        public const string Match30H = "Chelsea";
        public const string Match30A = "Arsenal";
        public const string Match31H = "Manchester City";
        public const string Match31A = "Brighton";
        public const string Match32H = "Chelsea";
        public const string Match32A = "Everton";
        public const string Match33H = "Watford";
        public const string Match33A = "Sheffield Utd";
        public const string Match34H = "Norwich";
        public const string Match34A = "Liverpool";
        public const string Match35H = "Bournemouth";
        public const string Match35A = "Aston Villa";
        public const string Match36H = "Leicester";
        public const string Match36A = "Sheffield Utd";
        public const string Match37H = "Leicester";
        public const string Match37A = "Norwich";
        public const string Match38H = "Newcastle";
        public const string Match38A = "Liverpool";
        public const string Match39H = "Manchester Utd";
        public const string Match39A = "Brighton";
    }
}
